package btl.ballgame.shared.libs;

public enum EntityType {
	ENTITY_PADDLE,
	ENTITY_BALL,
	ENTITY_BRICK_NORMAL,
	ENTITY_BRICK_HARD,
	ENTITY_BRICK_ITEM,
	ENTITY_BRICK_EXPLOSIVE,
	ENTITY_FALLING_ITEM,
	ENTITY_RIFLE_BULLET
}